@startuml
'https://plantuml.com/sequence-diagram


package "RTGS BATCH" {
  ControlMAgent - [Job Executor]
  [Job/Task]
}

package "Common Components" {
    [Maintenance Core]
    [Control-M API Service]    
}

package "RTGS Core Components" {
  MessageListener - [SPR]

  MessageListener - [BPR]

  MessageListener - [MPR]

  MessageListener - [QPR]

  MessageListener - [BackOffice]

  MessageListener - [Task Scheduler]
  
  MessageListener - [Report]
  
}

cloud {
  [ControlM/automation-api]
}

queue Solace {
   [Queue]
}

node "Control-M" {
    [Server]
}


database "MySql" {
  frame "rtgsdb" {
      [Records]
  }
}

[Server] --> ControlMAgent
[Job Executor] --> [Job/Task]
[Job/Task] --> [Queue]
[Job/Task] --> [Control-M API Service]
[Control-M API Service] --> [ControlM/automation-api]
[Queue] --> MessageListener
[ControlM/automation-api] --> [Server]
[BPR] --> [Records]
[QPR] --> [Records]
[SPR] --> [Records]
[MPR] --> [Records]
[BackOffice] --> [Records]
[Task Scheduler] --> [Records]
[Report] --> [Records]

@enduml
